### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

### ISSUE THREAD

**Issue by wang1528186571** [WhoTHU/Adversarial_camou#9]
在这段代码中会出现报错

> https://github.com/WhoTHU/Adversarial_camou/blob/7f97bc31355bf3cea317da736e9d06d6262adb7a/train.py#L600

```
precision: type=<class 'list'>, shape=(4810,)
recall: type=<class 'list'>, shape=(4810,)
avg: type=<class 'numpy.float64'>, shape=()
confs: type=<class 'numpy.ndarray'>, shape=(37, 130)
thetas: type=<class 'numpy.ndarray'>, shape=(37,)
  0%|                                                                                                                                                                                                    | 0/600 [07:07<?, ?it/s]
Traceback (most recent call last):
  File "/home/wang/Desktop/wjl-project-1/Adversarial_camou_pc/train.py", line 825, in <module>
    trainer.train()
  File "/home/wang/Desktop/wjl-project-1/Adversarial_camou_pc/train.py", line 636, in train
    np.savez(path, thetas=thetas, info=info)
  File "<__array_function__ internals>", line 200, in savez
  File "/home/wang/Anaconda3/envs/camou/lib/python3.8/site-packages/numpy/lib/npyio.py", line 615, in savez
    _savez(file, args, kwds, False)
  File "/home/wang/Anaconda3/envs/camou/lib/python3.8/site-packages/numpy/lib/npyio.py", line 716, in _savez
    val = np.asanyarray(val)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
```
我还尝试打印了他们的类型，但应该不是这个的问题，我将300改成1想进行测试的过程中出现了这个报错
辛苦您可以耐心解答

**Comment by WhoTHU** [comment]
您好，可否尝试替换成：
np.savez(path, thetas=thetas, info=np.asarray(info, dtype=object))

**Comment by wang1528186571** [comment]
> 您好，可否尝试替换成： np.savez(path, thetas=thetas, info=np.asarray(info, dtype=object))

非常感谢您的回复，确实解决了，但根据之前的issue，将numpy降级也需要
